/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMessag: typeof import('element-plus/es')['ElMessag']
}
