/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/statistic/AppCard.vue')['default']
    AppCardGroup: typeof import('./src/components/statistic/AppCardGroup.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppProgress: typeof import('./src/components/statistic/AppProgress.vue')['default']
    AppProgressGroup: typeof import('./src/components/statistic/AppProgressGroup.vue')['default']
    AppProgressGroupV2: typeof import('./src/components/statistic/AppProgressGroupV2.vue')['default']
    AppProgressV2: typeof import('./src/components/statistic/AppProgressV2.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileSelector: typeof import('./src/components/common/FileSelector.vue')['default']
    GeneralCard: typeof import('./src/components/GeneralCard.vue')['default']
    HeatCalendar: typeof import('./src/components/statistic/HeatCalendar.vue')['default']
    HeatCalendarCell: typeof import('./src/components/statistic/HeatCalendarCell.vue')['default']
    McpSettingItem: typeof import('./src/components/setting/McpSettingItem.vue')['default']
    OverviewCard: typeof import('./src/components/OverviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleDialog: typeof import('./src/components/setting/RuleDialog.vue')['default']
    SettingGroup: typeof import('./src/components/setting/SettingGroup.vue')['default']
    SettingItem: typeof import('./src/components/setting/SettingItem.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UpdateDialog: typeof import('./src/components/global/UpdateDialog.vue')['default']
    UpdateSettingItem: typeof import('./src/components/setting/UpdateSettingItem.vue')['default']
    WeeklyChart: typeof import('./src/components/statistic/WeeklyChart.vue')['default']
    WeeklyPolar: typeof import('./src/components/statistic/WeeklyPolar.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
